### PR TITLE
Hexadecimal Probe

### LINKED ISSUE #53: Feature Request: hex value probes
Add the ability to switch between binary and hex values for probes

### PR DESCRIPTION
**Pull request by Dallas-D**
Added ability for probes to display their value in binary or hexadecimal. This is expandable to decimal or other bases in the future. Fixes #53 

I've been having issues with installing the Java 9 SDK so I have not had a chance to build and debug. I will update when progress has been made.

### CODE REVIEW

**Comment by ausbin** [comment]
re: java 9, are you on debian/ubuntu? i believe in some versions the openjdk 9 in the repos does not include javafx: https://lists.debian.org/debian-java/2017/10/msg00032.html. kind of a mess, i had to install the oracle JDK (like extract the tarball to my homedir)

however i believe in newer versions this is fixed

**Comment by Dallas-D** [comment]
I got Java 9 working so it now builds. Hexadecimal values work really well. Decimal values, not so much. The way that GuiUtils draws values prevents the string from being longer than 8 characters, so it wraps to the next line, which doesn't really work for large decimal values. I put a temporary fix that lets the text wrap without looking too weird, but the drawValue probably needs a rewrite.

**Comment by Dallas-D** [comment]
I went ahead and added the new BASE property to the ConstantPeer since it was basically the same code as a Probe. The problem with decimal numbers still apply.

**Comment by Dallas-D** [comment]
Problem with wrapping decimal numbers is resolved.

**Comment by Dallas-D** [comment]
Bump for @ra4king to review this PR

**Comment by ra4king** [comment]
Sorry I missed this for years, I've been bad at keeping up with PRs. Can you fix the conflicts and we can then start proper rounds of reviews :)

**Comment by ra4king** [comment]
I finished the merge for you, thanks!

**Pull request merged**
