### PR TITLE
Support compiling and running under Java 8 & 9

### PR DESCRIPTION
**Pull request by ausbin**
Use some ugly reflection hacks to get this to compile and run on both Java 8 and 9. Oracle made some annoying changes to the JavaFX API that means we have to use reflection in a lot of cases here, unless I'm missing a better approach (I am not a Java guru by any means).

Some of this is ugly as heck, so I understand if you don't want to merge, but personally I'm gonna keep using this because Java 9 actually supports HiDPI on Linux and I want to be able to see what I'm doing

### CODE REVIEW

**Comment by ausbin** [comment]
mr. roi says no reflection

**Comment by ra4king** [comment]
Yeah sorry, I would really prefer having no reflection at all. Without these changes, this means CircuitSim does not even run on Java 9 correct?

**Comment by ausbin** [comment]
It does, you just can't compile on Java 9 or edit ROMs/RAMS

**Comment by ra4king** [comment]
How does it run on Java 9 but not compile? And the memory view window doesn't show up at all?

**Comment by ausbin** [comment]
When you compile on Java 9 the compiler can't locate any of the com.sun stuff. But when you run it after having compiling on 8, it just fails locating that stuff at runtime

"that stuff" is com.sun.javafx.scene.control.skin.TableHeaderRow and om.sun.javafx.scene.control.skin.TableHeaderRow

**Pull request closed without merging**
